### ISSUE TITLE
Bug: Cards stuck to top on mobile

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#24]
**Issue**
The cards stuck to top on mobile
Its as if the gravity is changed

**To Reproduce**
1. Go to harry potter page
2. Click on any person

**Expected behavior**
The Cards should gravitate to the center as happens on the desktop site

**Screenshots**
![WhatsApp Image 2021-06-19 at 4 30 06 PM](https://user-images.githubusercontent.com/68443055/122640188-ae170b00-d11b-11eb-9277-c95eff457566.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS14.6
 - Browser Safari, Chrome

**Comment by Dharmik48** [comment]
Will try to fix by tomorrow

**Comment by Dev-AkshDesai** [comment]
Just check it out in your phone if the issue happens in your device too

**Comment by Dharmik48** [comment]
> Just check it out in your phone if the issue happens in your device too

Doesn't happen in my device

**Comment by Dharmik48** [comment]
try again now if happens tell me

**Comment by Dev-AkshDesai** [comment]
Issue seems to have been gone👍

**Comment by Dev-AkshDesai** [comment]
Closing the issue
