### ISSUE TITLE
Issue With Pics

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#25]
**Describe the bug**
Issue With Pics.
The pics don't seem to come up in the contact cards when opened.

**To Reproduce**
1. Go to the site
2. Login as harry
2. Click on any persons name

**Expected behavior**
The card should show the pic as the D.P. on the top left as happened in previous versions.

**Screenshots**
![Screenshot (10)](https://user-images.githubusercontent.com/68443055/122641122-dd7c4680-d120-11eb-9e2f-17227c0b328e.png)

**Desktop:**
 - OS: Windows 10 10.0.19042 N/A Build 19042
 - Browser Google Chrome

**Comment by Dev-AkshDesai** [comment]
Try to see if this happens with your devices too.

If so, just try to solve it.

**Comment by Dharmik48** [comment]
This cause I haven't added the images

The URLs in JSON didnt seem to work so I didn't add images

**Comment by Dharmik48** [comment]
This isn't a big 

It's just that it isn't meant to happt

**Comment by Dev-AkshDesai** [comment]
Gotcha
