### ISSUE TITLE
The URL for image of Liliy Potter isn't working

### ISSUE THREAD

**Issue by Dharmik48** [Dev-AkshDesai/Family-Tree#28]
The URL for image of Liliy Potter isn't working. Please change it in the JSON file

**To Reproduce**
1. Go to 'harry/'
2. Click on 'harry.json'
3. Scroll down to 'Lily Potter'
4. Change the URL in 'photograph'

**Expected behavior**
Should properly work like the others.

**Screenshots**
![Screenshot 2021-06-19 225030_LI](https://user-images.githubusercontent.com/64529217/122650507-103e3300-d151-11eb-84d4-720a3ee592d9.jpg)

**Additional context**
Also if u can shorten the image URL of jame potter

**Comment by Dev-AkshDesai** [comment]
K gotcha

Will be solved by tomorrow 👍
