### ISSUE TITLE
Feature Request: Person Focus

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#49]
**Description**
when the harry.html is opened after the login page, it would be great of it would open with the person as the center

**Describe the solution you'd like**
If login name is entered as harry, the site should open with harry's card in the center and zoomed-in onto a small circle around him.

**Describe alternatives you've considered**

- We could open the whole tree and then have a zoom animation on the person

**Comment by Dharmik48** [comment]
sorry but this is not possible

**Comment by Dev-AkshDesai** [comment]
> sorry but this is not possible

Ya ya thats fine

Closing the issue
