### ISSUE TITLE
Preload Page

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#53]
**Please describe.**
If the tree has a lot of members, it could take a long time to render.

**Describe the solution you'd like**
If the tree has a lot of members, it could take a long time to render. In this scenario, a loading page would be good

**Describe alternatives you've considered**
We could have the images show up dynamically nut that would take a long time to implement.
We could have proxies. On startup, the images will be small resolution and on zooming in past a point, the proxies could change to the full sized version of that image. Again, lot of code and time to implement.

**Additional context**
Adding this could also save on data usage and increase the speed of the site by a significant amount and also reduce the compute usage on the client device as the device will have to render less pixels.

**Comment by Dharmik48** [comment]
u lovin it

**Comment by Dev-AkshDesai** [comment]
Closing issue

Great work btw
