### ISSUE TITLE
Background Update

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#54]
**Please describe.**
It would be great if there was a background for the tree page. Would just give it a bit more character and style.

**Describe the solution you'd like**
Just set a color/image/gradient as the background.

**Describe alternatives you've considered**
None😅

**Additional context**
We could also change the color of the cards to go with the new background color.

**Comment by Dharmik48** [comment]
added a dark bg for now

**Comment by Dev-AkshDesai** [comment]
Ohk

Great for now😉
