### ISSUE TITLE
Rounded Corners!!!!!!!!!!!

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#56]
**Please describe.**
Rounded corners. Need I say anything else?

**Describe the solution you'd like**
Make then....rounded
C'mon even Microsoft is doing it now😅

**Comment by Dharmik48** [comment]
better than windows 11😉

**Comment by Dev-AkshDesai** [comment]
Ayeeee

Love it😉

**Comment by Dev-AkshDesai** [comment]
Closing issue


Loved it
