### ISSUE TITLE
The left-partner tag

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#57]
**Please describe.**
Would be great if the left-partner tag could be removed.

**Describe the solution you'd like**
![WhatsApp Image 2021-06-22 at 6 36 21 PM](https://user-images.githubusercontent.com/68443055/122965389-c437fc00-d3a5-11eb-8541-15c2f5849618.jpeg)

**Comment by Dharmik48** [comment]
one more down

**Comment by Dev-AkshDesai** [comment]
Hell YEAH✊

**Comment by Dev-AkshDesai** [comment]
Closing issue
