### ISSUE TITLE
PPID tag

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#58]
**Describe the bug**
The PPID tag is visible in the contact-card and is unnecessary

**To Reproduce**
1. Go to harry's page
2. Click on any profile card
3. See error

**Expected behavior**
Just remove it😅

**Screenshots**
![WhatsApp Image 2021-06-22 at 6 34 28 PM](https://user-images.githubusercontent.com/68443055/122965642-0cefb500-d3a6-11eb-8c7e-786678d82910.jpeg)

**Comment by Dharmik48** [comment]
Say bye to the ppid

**Comment by Dev-AkshDesai** [comment]
😉

**Comment by Dev-AkshDesai** [comment]
Closing issue
