### ISSUE TITLE
Add more info to the Contact Card

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#59]
**Please describe.**
Info like the address and phone numbers and all could be added to the contact card

**Describe the solution you'd like**
it would be great if info like.....

- phone numbers
- email addresses
- mailing addresses
- nationalities
- and more.......
could be added
Since most of these fields are present in the json file, it could be just a matter of adding them to the code

**Comment by Dharmik48** [comment]
Done mate👍

**Comment by Dev-AkshDesai** [comment]
Tx🙂

**Comment by Dharmik48** [comment]
also now if the data the file doesnt have data for a field it show '-' instead of just being empty

**Comment by Dev-AkshDesai** [comment]
Closing issue
