### ISSUE TITLE
Make me GOLDENNNNNNN

### ISSUE THREAD

**Issue by Dev-AkshDesai** [Dev-AkshDesai/Family-Tree#60]
**Please describe.**
If possible, try to make my(and harry's) cards golden coz y now :D 

**MASSIVE FLEXXXXXXX** 😅

**Comment by Dharmik48** [comment]
DONE! atleast for Harry

**Comment by Dev-AkshDesai** [comment]
Closing the issue

**Comment by Dev-AkshDesai** [comment]
Closing the issue
